### ISSUE TITLE
"Network Error"

### ISSUE THREAD

**Issue by amir-gauss** [fescobar/allure-docker-service-ui#27]
hi
i setup 2 docker container:

`
**Core Service:**

docker run  --restart always -d --name allure-docker-service -p 6060:5050 -e CHECK_RESULTS_EVERY_SECONDS=1 -e KEEP_HISTORY=1  -v /home/test-server/Docker/allure-docker-java-testng-example/allure-results:/app/allure-results -v /home/test-server/Docker/allure-docker-java-testng-example/allure-reports:/app/default-reports frankescobar/allure-docker-service

**UI Container :**

docker run --restart always -d --name allure-docker-service-ui -p 5252:5252 -e ALLURE_DOCKER_PUBLIC_API_URL=http://192.168.84.51:6060/ frankescobar/allure-docker-service-ui
`

i have ping in allure-docker-service-ui to allure-docker-service(192.168.84.51) and i have telnet form port 6060 but 
when i try in browser error:
"Network Error"
Check if you have access to http://192.168.84.51:6060/allure-docker-service
Or pull the latest "frankescobar/allure-docker-service" API image (remove your current latest version)
{"message":"Network Error","name":"Error","stack":"Error: Network Error\n at e.exports (http://192.168.84.51:5252/static/js/2.fc83d11e.chunk.js:2:70398)\n at p.onerror (http://192.168.84.51:5252/static/js/2.fc83d11e.chunk.js:2:69367)","config":{"url":"/config","method":"get","headers":{"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"u9s6r5m23sr48418t6k8rco9cu"},"baseURL":"http://192.168.84.51:6060/allure-docker-service","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"withCredentials":true}}

i readed https://github.com/fescobar/allure-docker-service-ui/issues/4 and remove all image and get latest again but not resolved 
allure-docker-service-ui version : 7.0.3
allure-docker-service: 2.17.2

could you help me to find and check which parameter is missed?

**Comment by amir-gauss** [comment]
After try i find in my chrome result and error page cached and when i try another browser it's ok :-?
